"""Write a curated live-quality review from the real FastAPI explain route."""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path
from typing import Any

from fastapi.testclient import TestClient

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app.main import create_app  # noqa: E402

DEFAULT_CASES = ROOT / "eval" / "posts.yaml"
DEFAULT_OUT = ROOT / "docs" / "reviews" / "live_quality_review.md"


def public_cases(path: Path, limit: int) -> list[dict[str, Any]]:
    cases = json.loads(path.read_text(encoding="utf-8"))
    public = [case for case in cases if case.get("provenance") == "fixture_backed_public"]
    return public[: max(1, limit)]


def run_case(client: TestClient, case: dict[str, Any], api_key: str) -> dict[str, Any]:
    started = time.perf_counter()
    response = client.post(
        "/api/explain",
        json={
            "post_url": case["url"],
            "provider": "openai",
            "include_trace": True,
            "api_key": api_key,
        },
    )
    elapsed_ms = int((time.perf_counter() - started) * 1000)
    payload = response.json() if _is_json_response(response) else {}
    return summarize_case(case, payload, response.status_code, elapsed_ms)


def summarize_case(
    case: dict[str, Any],
    payload: dict[str, Any],
    status_code: int,
    elapsed_ms: int,
) -> dict[str, Any]:
    trace = _mapping(payload.get("trace"))
    bullets = _list(payload.get("bullets"))
    sources = _list(payload.get("sources"))
    warnings = _list(trace.get("warnings"))
    cited = sum(1 for bullet in bullets if _list(_mapping(bullet).get("source_ids")))
    return {
        "id": case.get("id"),
        "url": case.get("url"),
        "status_code": status_code,
        "latency_ms": elapsed_ms,
        "fallback_mode": trace.get("fallback_mode"),
        "adapter_mode": trace.get("adapter_mode"),
        "qdrant_status": qdrant_status(warnings),
        "meaningful": meaningful(status_code, bullets, cited, sources, trace),
        "bullets": bullets,
        "sources": sources,
        "warning_count": len(warnings),
    }


def qdrant_status(warnings: list[Any]) -> str:
    text = "\n".join(str(item) for item in warnings)
    if "qdrant_vector_store" in text:
        return "qdrant_vector_store"
    if "in_memory_fallback" in text or "qdrant_unavailable" in text:
        return "in_memory_fallback"
    return "not_reported"


def meaningful(
    status_code: int,
    bullets: list[Any],
    cited_count: int,
    sources: list[Any],
    trace: dict[str, Any],
) -> bool:
    return all(
        (
            status_code == 200,
            3 <= len(bullets) <= 5,
            cited_count == len(bullets),
            bool(sources),
            trace.get("fallback_mode") != "abstain",
            trace.get("adapter_mode") == "none",
        )
    )


def render_markdown(rows: list[dict[str, Any]]) -> str:
    pass_count = sum(1 for row in rows if row["meaningful"])
    lines = [
        "# Live Quality Review",
        "",
        "Generated by `make live-quality-review` against the real FastAPI",
        "explainer route. An OpenAI key was supplied locally through",
        "`OPENAI_API_KEY`; no key is written to this file.",
        "",
        f"- Cases run: `{len(rows)}`",
        f"- Meaningful pass count: `{pass_count}`",
        "",
        "| Case | Status | Bullets | Sources | Fallback | Qdrant | Latency | Meaningful |",
        "|---|---:|---:|---:|---|---|---:|---:|",
    ]
    for row in rows:
        lines.append(_summary_row(row))
    lines.extend(["", "## Returned Bullets", ""])
    for row in rows:
        lines.extend(_case_details(row))
    return "\n".join(lines).strip() + "\n"


def _summary_row(row: dict[str, Any]) -> str:
    return (
        f"| `{row['id']}` | {row['status_code']} | {len(row['bullets'])} | "
        f"{len(row['sources'])} | `{row['fallback_mode']}` | "
        f"`{row['qdrant_status']}` | {row['latency_ms']} ms | "
        f"{'yes' if row['meaningful'] else 'no'} |"
    )


def _case_details(row: dict[str, Any]) -> list[str]:
    lines = [f"### `{row['id']}`", "", f"URL: {row['url']}", ""]
    for index, bullet in enumerate(row["bullets"], start=1):
        item = _mapping(bullet)
        source_ids = ", ".join(str(source) for source in _list(item.get("source_ids")))
        lines.append(f"{index}. {item.get('text', '')} (`{source_ids}`)")
    lines.extend(["", "Sources:"])
    for source in row["sources"][:6]:
        item = _mapping(source)
        lines.append(f"- `{item.get('id')}` {item.get('title')} - {item.get('url')}")
    lines.append("")
    return lines


def _is_json_response(response: Any) -> bool:
    return "json" in response.headers.get("content-type", "").lower()


def _mapping(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Write live API quality review.")
    parser.add_argument("--cases", type=Path, default=DEFAULT_CASES)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--max-cases", type=int, default=6)
    return parser.parse_args()


def main() -> None:
    api_key = os.environ.get("OPENAI_API_KEY", "").strip()
    if not api_key:
        raise SystemExit("OPENAI_API_KEY is required to write the live quality review.")
    args = parse_args()
    client = TestClient(create_app())
    rows = [run_case(client, case, api_key) for case in public_cases(args.cases, args.max_cases)]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_markdown(rows), encoding="utf-8")
    print(json.dumps({"path": str(args.out), "cases": len(rows)}, indent=2))


if __name__ == "__main__":
    main()
